{
    'name': "Logistic Management",
    'summary': "Manage logistics operations",
    'description': """Module to manage shipments and logistics operations""",
    'author': "Hippo Parcel",
    'website': "https://www.hippoparcel.com",
    'category': 'Logistics',
    'version': '0.1',
    'depends': ['base'], 
    'data': [
        'security/ir.model.access.csv',
        # 'reports/shipment_reports.xml',
        'reports/shipment_report.xml',
        'reports/shipment_label.xml',
        'views/logistic_shipment.xml',
        'views/shipment_tracking.xml',
    ],    
    'installable': True,
    'application': True,
}
